portfolio4/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from portfolio4.views import handler404

urlpatterns = [
    path("", views.Home_items, name="home"),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('createpost', views.create_post, name='create_post'),
    path('post/<slug:slug>/like/', views.like_post, name='like_post'),
    path('comment/<slug:slug>/like/', views.like_comment, name='like_comment'),
    path('profile', views.profile, name='profile'),
    
]

handler404 = handler404

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

protfolio4_django/urls.py
from django.contrib import admin
from django.urls import path, include
#from portfolio4.views import get_index_page, create_post

urlpatterns = [
    path('admin', admin.site.urls),
    #path('', get_index_page, name='get_index_page'),
    #path('create-post', create_post, name='create_post'),
    path('', include('portfolio4.urls'), name='portfolio4_urls'),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
]

portfolio4/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User, AbstractUser
from cloudinary.models import CloudinaryField
from django.utils import timezone
from django.utils.text import slugify
import datetime
from datetime import date

# Create your models here.
class Category(models.Model):
    '''Model that stores categories'''
    name = models.CharField(max_length=40)
    slug = models.SlugField()
    image = CloudinaryField('image', default='placeholder')

    class Meta:
        ordering =['name']

    def __str___(self):
        return self.name

class Post(models.Model):
    '''Model that stores the post'''
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, related_name='author_posts')
    heading = models.CharField(max_length=150, unique=True)
    content = models.TextField(blank=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = CloudinaryField('image', default='placeholder')
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    categories = models.ManyToManyField(Category, blank=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering =['-creation_time']

    def __str__(self):
        return str(self.heading)

    def amount_of_likes(self):
        return self.likes.count()

    def like_post(self, user):
        self.likes.add(user)

    def unlike_post(self, user):
        self.likes.remove(user)
    
    def get_absolute_url(self):
        return reverse('post_detail', args=[self.slug])


class Comment(models.Model):
    '''Model that stores the comments on a post'''
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, related_name='author_comment', default=None)
    content = models.TextField(blank=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)
    image = CloudinaryField('image', default='placeholder')
    slug = models.SlugField(max_length=200, unique=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['creation_time']
    
    #override slug to make the slug unuiqe to be able to like mulitple comments
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.post}-{datetime.datetime.now()}')

        super().save(*args, **kwargs)

    def __str__(self):
        return f"Comment {self.content} by {self.author.first_name} {self.author.last_name}"

    def amount_of_likes(self):
        return self.likes.count()

    def like_comment(self, user):
        self.likes.add(user)

    def unlike_comment(self, user):
        self.likes.remove(user)
    
    def get_absolute_url(self):
        return reverse('post_detail', args=[self.slug])


class ExtendedUser(models.Model):
    '''Model that have one2one rel with user with custom fields'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profileImage = CloudinaryField('image', default='placeholder')

    def __str___(self):
        return self.user.username

    def get_profile_image(self):
        return self.profileImage.url

portfolio4/forms.py
from django import forms
from .models import Post, Comment, ExtendedUser
from django.contrib.auth.forms import UserChangeForm


class PostForm(forms.ModelForm):
    '''form for post a post'''
    class Meta:
        model = Post
        fields = ['heading', 'content', 'categories', 'image']

class CommentForm(forms.ModelForm):
    '''form for comment'''

    class Meta:
        model = Comment
        fields = ['content', 'image']


class ProfilePictureForm(forms.ModelForm):
    '''Form for profile picture'''
    class Meta:
        model = ExtendedUser
        fields = ['profileImage',]

portfolio4/views.py
from django.shortcuts import render,  HttpResponse, redirect, get_object_or_404
from .models import  Post, Comment, Category, ExtendedUser
from .forms import PostForm, CommentForm, ProfilePictureForm
from django.views import generic, View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from allauth.account.forms import ChangePasswordForm, SetPasswordForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.utils.text import slugify
import datetime

# Create your views here.


def create_post(request):
    '''View for create post'''
    post_form = PostForm()

    if request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            instance = post_form.save(commit=False)
            instance.author = request.user
            instance.image = request.FILES['image']

            # Generate a unique slug
            base_slug = slugify(instance.heading)
            unique_slug = base_slug
            count = 1

            while Post.objects.filter(slug=unique_slug).exists():
                # Slug already exists, append a count to make it unique
                count += 1
                unique_slug = f'{base_slug}-{count}'

            instance.slug = unique_slug
            instance.save()

            return redirect('create_post')

    return render(request, 'create_post.html', {'post_form': post_form})


class CategoryList(generic.ListView):
    '''view for listing categories'''
    model = Category
    queryset = Category.objects.order_by('name')
    template_name = 'base.html'
    paginate_by = 10

class PostList(generic.ListView):
    '''view to show post in list '''
    model = Post
    queryset = Post.objects.order_by('creation_time')
    template_name = 'base.html'
    paginate_by = 5

def Home_items(request):
       categories = Category.objects.all()
       posts = Post.objects.all()
       context = {
              'categories': categories,
              'posts': posts
       }
       return render(request, 'index.html', context)

class CategoryDetail(View):
    '''view to display category dettail Work in progress.... '''
    def get(self, request, slug, *args, **kwargs):
        queryset = Category.objects
        categories = get_object_or_404(queryset, slug=slug)

    pass

@login_required
def like_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    
    if request.user in post.likes.all():
        post.unlike_post(request.user)
    else:
        post.like_post(request.user)

    return redirect('post_detail', slug=slug)

def post_detail(request, slug):
    '''view for post detail and comment form'''
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(approved=True).order_by("-creation_time")
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST, request.FILES)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.author = request.user
            #Todo fix bug 
            #new_comment.image = request.FILES['image']
            new_comment.save()
            return redirect('post_detail', slug=slug)
    else:
        comment_form = CommentForm()

        
    return render(request, 'post_detail.html', {'post': post, 'comments': comments, 'comment_form': CommentForm()})


@login_required
def like_comment(request, slug):
    comment = get_object_or_404(Comment, slug=slug)
    
    if request.user in comment.likes.all():
        comment.unlike_comment(request.user)
    else:
        comment.like_comment(request.user)

    return redirect('post_detail', slug=comment.post.slug)

def handler404(request, exception):
    '''handles 404 page'''

    return render(request, '404.html', status=404)


@login_required
def profile(request):
    '''view for profile page with it's forms '''
    try:
        extended_user = request.user.extendeduser  # get or create ExtendedUser
    except ExtendedUser.DoesNotExist:
        extended_user = ExtendedUser(user=request.user)
        extended_user.save()
    #profile image form
    if request.method == 'POST':
        profile_picture_form = ProfilePictureForm(request.POST, request.FILES)

        if profile_picture_form.is_valid():
            extended_user.profileImage = profile_picture_form.cleaned_data['profileImage']
            extended_user.save()
            return redirect('profile')

    else:
        profile_picture_form = ProfilePictureForm()

    # user change form
    password_change_form = PasswordChangeForm(request.user)

    if request.method == 'POST':
        password_change_form = PasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)  # Update session to prevent logout
            messages.success(request, 'Your password was successfully updated!')
            return redirect('account:profile')

    return render(request, 'account/profile.html', {'password_change_form': password_change_form,
                                                     'profile_picture_form': profile_picture_form,})

portfolio4/templates/portfolio4/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        Create a post
    </h1>
    <form method="post" action="create-post">
        {% csrf_token %}
        {{ form }}
        <div>
            <p>
              <button type="submit">Add item</button>
            </p>
        </div>
    </form>

   <!-- {% if user.is.authenticated %}
    <form method="post" action="create-post">
        {% csrf_token %}
        <div>
            <p>
                <label for="id_heading">Name: Header</label>
                <input type="text" id="id_heading" name="post_heading" />
            </p>
        </div>
        <div>
            <p>
                <label for="id_content">Name: content</label>
                <input type="text" id="id_content" name="post_content" />
            </p>
        </div>
        <div>
           
            <p>
                <button type="submit">Add item</button>
            </p>
        </div> 
    </form>
    {% else %}
    <p>plese login to post</p> 
    {% endif %}-->

</body>
</html>

portfolio4/templates/portfolio4/home_page.html
{% extends ‘base.html’ %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script  src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <script src="https://kit.fontawesome.com/52e37cb4eb.js" crossorigin="anonymous"></script>
    <title>Luna</title>
</head>
<body>
    <main> 
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand me-lg-5 " href="home_page.html">
                    <img src="{% static '/images/luna-logo_transparent.png' %}" class="logo-image img-fluid" alt="Luna-logo">
                </a>

                <form action="#" method="get" class="search-form flex-fill me-3" role="search">
                    <div class="input-group input-group-lg">
                        <input name="search" type="search" class="form-control" id="search-topics" placeholder="Search topics"
                            aria-label="Search">

                        <button type="submit" class="form-control" id="submit">
                            <i class="fa-brands fa-searchengin fa-flip fa-xl" style="color: #D4DCDE;"></i>
                        </button>
                    </div>
                </form>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="/">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/">Log in</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/">Topics</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/">Contact</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/">About luna</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </main>

    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-12 mb-5 mb-lg-0">
                    <div class="subscribe-form-wrap">
                        <h6>Subscribe and get news updates</h6>

                        <form class="subscribe-form" action="#" method="post" role="form">
                            <input type="email" name="subscribe-email" id="subscribe-email" pattern="[^ @]*@[^ @]*"
                                class="form-control" placeholder="Email Address" required="">

                            <div class="col-lg-12 col-12">
                                <button type="submit" class="form-control" id="submit">Subscribe</button>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-md-0 mb-lg-0">
                    <h6 class="mb-3">Contact</h6>

                    <p class="mb-2"><strong class="d-inline me-2">Phone:</strong> 0000000000</p>

                    <p>
                        <strong class="d-inline me-2">Email:</strong>
                        <a href="#">mail@lunacamillath@gmail.com</a>
                    </p>
                </div>

                <div class="col-lg-3 col-md-6 col-12">
                    <h6 class="mb-3">Social</h6>

                    <ul class="social-icon">
                        <li>
                            <a href="https://instagram.com" target="_blank" aria-label="see updated on instagram" rel="noopener"> <i
                                    class="fa-brands fa-instagram fa-2x"></i></a>
                        </li>
                        <li>
                            <a href="https://twitter.com" target="_blank" aria-label="see updated on twitter" rel="noopener"> <i
                                    class="fa-brands fa-twitter fa-2x"></i></a>
                        </li>
                        <li>
                            <a href="https://facebook.com" target="_blank" aria-label="see updated on facebook" rel="noopener"> <i
                                    class="fa-brands fa-facebook-f fa-2x"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
       <div class="container pt-5">
            <div class="row">

                <div class="col-lg-2 col-md-3 col-12">
                    <a class="navbar-brand" href="/">
                        <img src="{% static '/images/luna-logo_transparent.png' %}" class="logo-image img-fluid" alt="footer luna logo">
                    </a>
                </div>
                <div class="col-lg-3 col-12">
                    <p class="mb-0">Copyright © 2023 Luna
                    </p> 
                </div>
            </div>
        </div>
    </footer>
   <!-- <h1>
        This is home template 
    </h1>
    <table>
        {% for post in posts %}
        <tr>
            <td>{{ post.author }}</td>
            <td>{{ post.heading }}</td>
            <td>{{ post.content }}</td>
            <td>{{ post.comment.comment }}</td>
        </tr>
        {% empty %}
        <tr><td>no posts</td></tr>
        {% endfor %}
    </table>
    <a href="/create-post">create post</a> -->
</body>
</html>